spring.application.name=CampusCarTrade
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/campus_car_trade
spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

campus-car-trade.alioss.accessKeyId=LTAI5tA1z7CVhKLjx8jUsHBc

campus-car-trade.alioss.bucketName=ame=whpz-campus-car-trade
campus-car-trade.alioss.endpoint=oss-cn-hangzhou.aliyuncs.com


campus-car-trade.jwt.admin-secret-key=cctv
campus-car-trade.jwt.admin-ttl=7200000
campus-car-trade.jwt.admin-token-name=token